# Generated by Django 3.2.18 on 2023-03-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0002_auto_20230328_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(null=True),
        ),
    ]
