# Generated by Django 3.2.18 on 2023-03-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0007_auto_20230329_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='title',
            new_name='name',
        ),
    ]
