# Generated by Django 3.2.18 on 2023-03-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0008_rename_title_channel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='name',
            new_name='title',
        ),
    ]
