# Generated by Django 3.2.18 on 2023-04-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0010_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='privat',
            field=models.BooleanField(blank=True),
        ),
    ]
