# Generated by Django 3.2.18 on 2023-04-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0013_alter_channel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
