# Generated by Django 3.2.18 on 2023-04-02 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0015_remove_channel_privat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='guests',
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, default='Null', related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
