# Generated by Django 3.2.18 on 2023-04-02 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0016_auto_20230402_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='privat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
