# Generated by Django 3.2.18 on 2023-04-02 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0017_auto_20230402_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guests', to=settings.AUTH_USER_MODEL),
        ),
    ]
