# Generated by Django 3.2.18 on 2023-04-03 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0018_channel_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(default=None, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
