# Generated by Django 3.2.18 on 2023-04-03 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0019_auto_20230403_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_members': True}, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
