# Generated by Django 3.2.18 on 2023-04-03 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0020_auto_20230403_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'members': True}, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
