# Generated by Django 3.2.18 on 2023-04-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0022_alter_channel_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='privat',
        ),
    ]
