# Generated by Django 3.2.18 on 2023-04-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0024_alter_channel_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
