# Generated by Django 3.2.18 on 2023-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0027_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userImage',
            field=models.ImageField(default='avatar.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
