# Generated by Django 3.2.18 on 2023-04-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0028_auto_20230409_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='members',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userImage',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
