# Generated by Django 3.2.18 on 2023-04-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0029_auto_20230411_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='imgage',
        ),
    ]
