# Generated by Django 3.2.18 on 2023-04-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0030_rename_img_post_imgage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgage',
        ),
    ]
