# Generated by Django 3.2.18 on 2023-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0034_auto_20230411_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loggedin',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
