# Generated by Django 3.2.18 on 2023-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0035_user_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loggedin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
