# Generated by Django 3.2.18 on 2023-04-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0038_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='featured_image',
            new_name='image',
        ),
    ]
