# Generated by Django 3.2.18 on 2023-04-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0039_rename_featured_image_chat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slackbook_user.chat'),
        ),
    ]
