# Generated by Django 3.2.18 on 2023-04-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0042_alter_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='body',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
