# Generated by Django 3.2.18 on 2023-04-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0043_alter_chat_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='body',
            field=models.TextField(blank=True, default=' ', max_length=200),
        ),
    ]
