# Generated by Django 3.2.18 on 2023-04-20 15:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('slackbook_user', '0045_alter_chat_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
