# Generated by Django 3.2.18 on 2023-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0046_channel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
