# Generated by Django 3.2.18 on 2023-04-21 07:10

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('slackbook_user', '0047_alter_channel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
