# Generated by Django 3.2.18 on 2023-04-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0048_alter_channel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='content',
        ),
    ]
