# Generated by Django 3.2.18 on 2023-04-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0050_post_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slackbook_user.chat'),
        ),
    ]
