# Generated by Django 3.2.18 on 2023-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0053_alter_post_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='username', max_length=200, unique=True),
        ),
    ]
