# Generated by Django 3.2.18 on 2023-04-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0054_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='host', max_length=200, unique=True),
        ),
    ]
