# Generated by Django 3.2.18 on 2023-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0056_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='host', max_length=200),
        ),
    ]
