# Generated by Django 3.2.18 on 2023-04-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0060_remove_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='slug',
        ),
    ]
