# Generated by Django 3.2.18 on 2023-04-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0061_remove_chat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=models.EmailField(max_length=254, unique=True), max_length=200, unique=True),
        ),
    ]
