# Generated by Django 3.2.18 on 2023-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0063_remove_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
