# Generated by Django 3.2.18 on 2023-04-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0068_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userDefImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
