# Generated by Django 3.2.18 on 2023-04-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0069_user_userdefimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userDefImage',
            field=models.ImageField(blank=True, default='images/avatar_rzmssh', null=True, upload_to=''),
        ),
    ]
