# Generated by Django 3.2.18 on 2023-04-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbook_user', '0072_remove_user_userdefimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
